### ISSUE TITLE
On all pages but front and any re-save of a page, permissions issues with images

### ISSUE THREAD

**Issue by elmcip** [elmcip/elmcip_elo#10] opened 2015-04-16 19:03 UTC
@cure @steinmb There is some permissions issue with the images on the conference.eliterature.org site. My guess is the files have had permissions rewritten in transfer, or something like that? In any case, images break on pages other than front and on any save of page.

![screenshot 2015-04-16 20 51 48](https://cloud.githubusercontent.com/assets/5831053/7188957/c6a36a1c-e47b-11e4-9afd-ee3f9b5d2fa6.png)

**Comment by elmcip** [comment] 2015-04-16 19:07
@cure For example: http://conference.eliterature.org/2015/venues

The logo block is broken.

**Comment by cure** [comment] 2015-04-16 19:18
Ah, interesting. It seems the theme inserts an extra /2015 at the start of all the logo links. That shouldn't be there. I've worked around it with a symlink (so the logos are working again on the site), but maybe the theme can be fixed?

**Comment by elmcip** [comment] 2015-04-16 19:20
Thanks Ward. @steinmb can you hit the theme fix?

**Comment by steinmb** [comment] 2015-04-16 20:32
@elmcip the error on temp:// are normally caused by permission issues of the file system. You normally have warnings on:

/admin/config/media/file-system
/admin/reports/status

Make sure the web server are allowed to write to Drupal "Public file system path" (public://) normally /sites/default/files and all directories. Make sure Apache (or what you are using) can write here. Normally we just alter the owner for the files and dir to what ever user the webserver run as.

**Comment by steinmb** [comment] 2015-04-16 20:34
The logo block? What block it that? http://conference.eliterature.org/2015/venues only gave me a 404.

**Comment by elmcip** [comment] 2015-04-16 20:56
@cure the fix breaks things -- the http://conference.eliterature.org/2015/venues page now gets a 404 -- there is some issue here with the way the server is handling Drupal path rewrites?

**Comment by cure** [comment] 2015-04-16 21:06
Okay, I've removed the symlink. The problem is with the theme - all the logo img src links are missing a leading slash, that is why the images are not loading.

**Comment by steinmb** [comment] 2015-04-16 21:17
@cure Ah, Did a quick fix for that. Look at commit 25ed7a2. Run a git pull and see if that take care of the logos from the theme.

**Comment by cure** [comment] 2015-04-17 00:47
On Thu, Apr 16, 2015 at 02:17:12PM -0700, Stein Magne Bjørklund wrote:

> @cure Ah, Did a quick fix for that. Look at commit 25ed7a2. Run a git pull and see if that take care of the logos from the theme.

Excellent, that fixes it.

Thanks,
Ward.

## 

http://corehost.us
Colocation, dedicated and virtual servers with a heart for free software.

**Comment by elmcip** [comment] 2015-04-25 03:28
@cure Did the fix get pushed to the live site? 

Look at: http://conference.eliterature.org/2015/venues

The sponsor logos on the bottom block break after save.

**Comment by cure** [comment] 2015-04-25 19:47
@elmcip yes running HEAD. Looks like this still isn't fixed; all the image links are wrong (no leading slash).

**Comment by elmcip** [comment] 2015-04-26 02:31
@cure I just pulled the current version from the repository, and it does not seem to have the same issue as the live site. I think @steinmb pushed the change to the repository. Did you pull from the repo to the live site?

**Comment by cure** [comment] 2015-04-26 15:18
@elmcip yes, we're on master/HEAD like I said:

<pre>
# git pull
Already up-to-date.
# git remote show origin
* remote origin
  Fetch URL: git@github.com:elmcip/elmcip_elo.git
  Push  URL: git@github.com:elmcip/elmcip_elo.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
# git status
# On branch master
nothing to commit (working directory clean)
</pre>

**Comment by elmcip** [comment] 2015-04-26 15:31
@steinmb can you give a little help on this: http://conference.eliterature.org/2015/venues sponsor links at foot of page still broken.

**Comment by elmcip** [comment] 2015-04-27 02:00
@steinmb leading slash does not appear here, causing problem. Where do we fix the path? ![path_issue](https://cloud.githubusercontent.com/assets/5831053/7340626/2b82ff92-ecc4-11e4-8902-844559a1ff96.png)

**Comment by steinmb** [comment] 2015-05-01 15:03
Back from two weeks vacation:

Let's try to improve it then. Commit f755dcd97ff34142d2607400f086dc8d9c76c9c improve picking up sites running on sub directories. Pls. verify this by pulling it into the live site. Worked OK running on multiple sub directories in my local sandbox.

**Comment by cure** [comment] 2015-05-06 00:35
@steinmb thank you, it's fixed now.

**Closed as completed** 2015-05-06 00:35 UTC
